openapi: 3.0.3
info:
  title: Booking and Test Drive Service API
  version: 1.0.0
  description: API for handling vehicle bookings and test drive appointments
servers:
  - url: http://localhost:8003
tags:
  - name: TestDrive
    description: Operations related to test drive bookings
  - name: Booking
    description: Operations related to vehicle bookings
paths:
  /testdrives:
    get:
      tags:
        - TestDrive
      summary: Get a list of available test drives
      operationId: getTestDrives
      parameters:
        - name: vehicle_id
          in: query
          required: false
          schema:
            type: string
          description: Filter by vehicle ID
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Filter by date of test drive
      responses:
        '200':
          description: List of available test drives
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestDrive'
        '400':
          description: Invalid request
  /testdrives/{id}:
    get:
      tags:
        - TestDrive
      summary: Get details of a specific test drive appointment
      operationId: getTestDriveById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the test drive appointment
      responses:
        '200':
          description: Details of the test drive
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestDrive'
        '404':
          description: Test drive not found
  /testdrives/book:
    post:
      tags:
        - TestDrive
      summary: Book a test drive appointment
      operationId: bookTestDrive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestDriveBooking'
      responses:
        '201':
          description: Test drive successfully booked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestDrive'
        '400':
          description: Invalid booking request
  /bookings:
    get:
      tags:
        - Booking
      summary: Get a list of vehicle bookings
      operationId: getBookings
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
          description: Filter by user ID
      responses:
        '200':
          description: List of vehicle bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '400':
          description: Invalid request
  /bookings/{id}:
    get:
      tags:
        - Booking
      summary: Get details of a specific vehicle booking
      operationId: getBookingById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the vehicle booking
      responses:
        '200':
          description: Details of the vehicle booking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '404':
          description: Booking not found
  /bookings/book:
    post:
      tags:
        - Booking
      summary: Book a vehicle for purchase
      operationId: bookVehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '201':
          description: Vehicle successfully booked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '400':
          description: Invalid booking request
components:
  schemas:
    TestDrive:
      type: object
      properties:
        id:
          type: string
          example: "1"
        vehicle_id:
          type: string
          example: "101"
        user_id:
          type: string
          example: "5001"
        date:
          type: string
          format: date
          example: "2023-09-15"
        time:
          type: string
          example: "10:30"
        status:
          type: string
          example: "Confirmed"
    TestDriveBooking:
      type: object
      required:
        - vehicle_id
        - user_id
        - date
        - time
      properties:
        vehicle_id:
          type: string
          example: "101"
        user_id:
          type: string
          example: "5001"
        date:
          type: string
          format: date
          example: "2023-09-15"
        time:
          type: string
          example: "10:30"
    Booking:
      type: object
      properties:
        id:
          type: string
          example: "1"
        user_id:
          type: string
          example: "5001"
        vehicle_id:
          type: string
          example: "101"
        booking_date:
          type: string
          format: date
          example: "2023-09-10"
        status:
          type: string
          example: "Confirmed"
    BookingRequest:
      type: object
      required:
        - user_id
        - vehicle_id
      properties:
        user_id:
          type: string
          example: "5001"
        vehicle_id:
          type: string
          example: "101"
          
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
