apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-svc
  template:
    metadata:
      labels:
        app: booking-svc
    spec:
      containers:
      - name: booking-svc
        image: booking-svc:latest  # Ensure this image is available locally or update to the correct image
        imagePullPolicy: Never
        ports:
        - containerPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: booking-svc
spec:
  selector:
    app: booking-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003  # Updated to match the container port in booking-svc
      nodePort: 30084   # Updated nodePort for booking-svc
  type: NodePort
