apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: pradyumnakmbits/gateway-svc:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30081
  type: NodePort
# Updated at Mon Nov 11 12:28:44 UTC 2024
# Updated at Sun Dec  8 08:09:23 UTC 2024
# Updated at Sun Dec  8 08:33:40 UTC 2024
# Updated at Sun Dec  8 08:44:55 UTC 2024
# Updated at Sun Dec  8 09:00:27 UTC 2024
