apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-svc
  template:
    metadata:
      labels:
        app: support-svc
    spec:
      containers:
      - name: support-svc
        image: pradyumnakmbits/support-svc:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8004

---
apiVersion: v1
kind: Service
metadata:
  name: support-svc
spec:
  selector:
    app: support-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004  # Updated to match the container port in booking-svc
      nodePort: 30085   # Updated nodePort for booking-svc
  type: NodePort
# Updated at Mon Nov 11 12:06:26 UTC 2024
# Updated at Sun Dec  8 08:01:28 UTC 2024
# Updated at Sun Dec  8 10:49:04 UTC 2024
