apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-svc
  template:
    metadata:
      labels:
        app: customer-svc
    spec:
      containers:
      - name: customer-svc
        image: customer-svc:latest  # Using the locally built image
        imagePullPolicy: Never
        ports:
        - containerPort: 8007

---
apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  selector:
    app: customer-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8007
      nodePort: 30082
  type: NodePort
