apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-svc
  template:
    metadata:
      labels:
        app: feedback-svc
    spec:
      containers:
      - name: feedback-svc
        image: feedback-svc:latest  # Using the locally built image
        imagePullPolicy: Never
        ports:
        - containerPort: 8006

---
apiVersion: v1
kind: Service
metadata:
  name: feedback-svc
spec:
  selector:
    app: feedback-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8006
      nodePort: 30087
  type: NodePort
