apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autohub-services
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pradyumnabits/autochoice-app.git
    targetRevision: HEAD
    path: latest/deployment/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: autohub

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true