openapi: 3.0.0
info:
  title: Customer Service API
  description: API for managing customer profiles
  version: 1.0.0

servers:
  - url: http://localhost:8007
    description: local server

paths:
  /ping:
    get:
      summary: Health check
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: pong-customer-svc

  /customers:
    get:
      summary: List all customers
      responses:
        "200":
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerResponse"
    post:
      summary: Create a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "201":
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

  /customers/{userName}:
    get:
      summary: Retrieve a customer by userName
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Customer found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "404":
          description: Customer not found
    put:
      summary: Update an existing customer
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "200":
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "404":
          description: Customer not found
    delete:
      summary: Soft delete a customer by marking profile status as 'inactive'
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Customer deleted successfully
        "404":
          description: Customer not found

  /customers/{userName}/status:
    put:
      summary: Update a customer's profile status
      parameters:
        - name: userName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [active, inactive]
                  default: active
      responses:
        "200":
          description: Profile status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userName:
                    type: string
                  profileStatus:
                    type: string
        "404":
          description: Customer not found

components:
  schemas:
    Customer:
      type: object
      required:
        - userName
        - firstName
        - lastName
        - email
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        profileStatus:
          type: string
          enum: [active, inactive]
          default: active

    CustomerResponse:
      type: object
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        profileStatus:
          type: string
          enum: [active, inactive]
